# Generated by Django 5.0 on 2025-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('teacher', 'Викладач'), ('researcher', 'Дослідник')], max_length=20, verbose_name='Роль'),
        ),
    ]
