# Generated by Django 5.0 on 2025-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True, verbose_name='Назва')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата додавання')),
            ],
            options={
                'verbose_name': 'Заклад освіти',
                'verbose_name_plural': 'Заклади освіти',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='scopus',
            field=models.URLField(blank=True, verbose_name='Scopus'),
        ),
        migrations.AddField(
            model_name='user',
            name='web_of_science',
            field=models.URLField(blank=True, verbose_name='Web of Science'),
        ),
        migrations.AlterField(
            model_name='user',
            name='education_level',
            field=models.CharField(choices=[('incomplete_secondary', 'Неповна середня освіта'), ('secondary', 'Середня освіта'), ('junior_bachelor', 'Фаховий молодший бакалавр'), ('bachelor', 'Бакалавр'), ('master', 'Магістр'), ('phd', 'Аспірант'), ('candidate', 'Кандидат наук'), ('doctor_phd', 'Доктор філософії (PhD)'), ('doctor', 'Доктор наук')], default='bachelor', max_length=30, verbose_name='Рівень освіти'),
        ),
    ]
